<% project_name = 'rails-api-template' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <LastMinuteBnb>_development

test:
  <<: *default
  database: <LastMinuteBnb>_test
